### ISSUE TITLE
bedroom_temperature_24_hours_ago

### ISSUE THREAD

**Issue by johntdyer** [parautenbach/Home-Automation#3]
Hello,

 Really like some of your configs, thank you for sharing.   I have been modeling some items in my own home after them.  I do have one question so far, I see the automation at the bottom of environment.yaml as follows

```yaml

  # polling should be turned off for this sql sensor (via the ui)
  # https://github.com/home-assistant/core/issues/71563
  - alias: "Update Bedroom Temperature 24 Hours Ago"
    id: "3a6fa2e6-355b-405b-b53a-5d52d8e3aa84"
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.bedroom_ht_temperature
      - platform: time_pattern
        minutes: "/30"
      - platform: homeassistant
        event: start
    action:
      - service: homeassistant.update_entity
        target:
          entity_id: sensor.bedroom_temperature_24_hours_ago

````

but what I dont see is where `sensor.bedroom_temperature_24_hours_ago` is defined / created... am I missing something ? 

Regards
